apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-and-test
spec:
  description: |
    This step runs the script that deploys RHDH and runs the tests
  params:
    - name: kubeconfig
      default: ""
      description: "config required to use kubectl/oc"
    - name: username
      default: ""
      description: "cluster username to use for login"
    - name: password
      default: ""
      description: "cluster password to use for login"
    - name: apiServerUrl
      default: ""
      description: "cluster apiServerUrl to use for login"
  steps:
    - name: deploy-and-test
      image: ubuntu
      env:
        - name: kubeconfig
          value: $(params.kubeconfig)
        - name: username
          value: $(params.username)
        - name: password
          value: $(params.password)
      script: |
        #!/usr/bin/env bash
        export HOME WORKSPACE
        HOME=/tmp
        WORKSPACE=$(pwd)
        cd /tmp || exit
        echo ${apiServerUrl}
        oc login ${apiServerUrl} --username=${username} --password=${password}
        oc whoami --show-console
        # curl -sSLO https://raw.githubusercontent.com/rhdh-bot/openshift-helm-charts/redhat-developer-hub-1.2-150-CI/installation/install.sh && chmod +x install.sh
        # ./install.sh 1.2-150-CI --namespace showcase --chartrepo
        

