apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-and-test
spec:
  description: |
    This step runs the script that deploys RHDH and runs the tests
  params:
    - name: RHDH_SECRETS
      default: rhdh-secrets
  volumes:
    - name: rhdh-secrets
      secret: 
        secretName: $(params.RHDH_SECRETS)
  steps:
    - name: deploy-and-test
      image: quay.io/redhat-user-workloads/rh-ee-oaljalju-tenant/test2:c5ede9a7b2caa42e32f745bea5b2c96d942cd06c
      volumeMounts:
        - mountPath: /etc/secrets
          name: rhdh-secrets
          readOnly: true
      env:
        - name: RHDH_SECRETS
          value: $(params.RHDH_SECRETS)
      script: |
        #!/usr/bin/env bash
        export HOME WORKSPACE
        HOME=/tmp
        WORKSPACE=$(pwd)
        cd /tmp || exit

        API_SERVER_URL=$(cat /etc/secrets/API_SERVER_URL)
        USERNAME=$(cat /etc/secrets/USERNAME)
        PASSWORD=$(cat /etc/secrets/PASSWORD)
        oc login ${API_SERVER_URL} --username=${USERNAME} --password=${PASSWORD}
        oc whoami --show-console
        # curl -sSLO https://raw.githubusercontent.com/rhdh-bot/openshift-helm-charts/redhat-developer-hub-1.2-150-CI/installation/install.sh && chmod +x install.sh
        # ./install.sh 1.2-150-CI --namespace showcase --chartrepo
        

