apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-and-test
spec:
  description: |
    This step runs the script that deploys RHDH and runs the tests
  params:
    - name: rhdh_secrets
      default: rhdh-secrets
  volumes:
    - name: $(params.rhdh_secrets)
      secret: 
        secretName: $(params.rhdh_secrets)
  steps:
    - name: deploy-and-test
      image: quay.io/redhat-user-workloads/rh-ee-oaljalju-tenant/konflux-test-poc:73138599dd32ca889204243c83fd8ecf42f2ff06 # Container image with OC installed
      volumeMounts:
        - mountPath: "/etc/secrets"
          name: $(params.rhdh_secrets)
          readOnly: true
      env:
        - name: RHDH_SECRETS
          value: $(params.rhdh_secrets)
      script: |
        #!/usr/bin/env bash
        set -xe
        export HOME WORKSPACE
        HOME=/tmp
        WORKSPACE=$(pwd)
        cd /tmp || exit

        API_SERVER_URL=$(cat /etc/secrets/API_SERVER_URL)
        USERNAME=$(cat /etc/secrets/USERNAME)
        PASSWORD=$(cat /etc/secrets/PASSWORD)
        oc login ${API_SERVER_URL} --username=${USERNAME} --password=${PASSWORD}

        export BASE_URL="redhat-developer-hub-showcase.$(oc get ingresses.config/cluster -o jsonpath='{.spec.domain}')"
        
        if oc get namespace showcase >/dev/null 2>&1; then
          echo "Namespace showcase already exists! refreshing namespace"
          oc delete namespace showcase
        fi

        curl -sSLO https://raw.githubusercontent.com/rhdh-bot/openshift-helm-charts/redhat-developer-hub-1.3-124-CI/installation/install.sh && chmod +x install.sh
        ./install.sh 1.3-124-CI --namespace showcase --chartrepo

        sleep 300

        git clone https://github.com/Omar-AlJaljuli/janus-idp-backstage-showcase-.git
        cd janus-idp-backstage-showcase- || exit
        git checkout "Konflux-test-1" || exit
        cd e2e-tests/
        yarn install
        yarn playwright install
        
        cd playwright/e2e/
        yarn playwright test ./konflux-poc.spec.ts
        

