apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: publish-helm
spec:
  description: |
    This step runs script 
  params:
  - name: SOURCE_ARTIFACT
    default: ""
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
    - name: publish
      image: ubuntu
      workdir: /var/workdir/
      script: |
        #!/usr/bin/env bash

        ls -la
        ls ./source
