apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: konflux-showcase-ci-ephemeral
spec:
  description: |
    integration test which requests an ephemeral cluster provisioned by konflux and deployes RHDH
    using Helm and runs the e2etest suite onto that instance
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: provision-eaas-space
      runAfter:
        - parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
    - name: openshift-ci-tests
      runAfter:
        - provision-cluster
      taskSpec:
        params:
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(tasks.provision-cluster.results.clusterName)"
              - name: credentials
                value: credentials
          - name: deploy-and-test
            image: quay.io/redhat-user-workloads/rh-ee-oaljalju-tenant/test2:5bca399965bf7bebe60d7739ccaecbf46ad60e60 # Container image with OC installed
            env:
              - name: USERNAME
                value: "$(steps.get-kubeconfig.results.username)"
              - name: PASSWORD_PATH
                value: "/credentials/$(steps.get-kubeconfig.results.passwordPath)"
              - name: API_SERVER_URL
                value: "$(steps.get-kubeconfig.results.apiServerURL)"
            volumeMounts:
              - name: credentials
                mountPath: /credentials
            script: |
              #!/usr/bin/env bash
              export HOME WORKSPACE
              HOME=/tmp
              WORKSPACE=$(pwd)
              cd /tmp || exit
              

              check_backstage_running() {
                local release_name=$1
                local namespace=$2
                local url=$3

                local max_attempts=30
                local wait_seconds=30

                echo "Checking if Backstage is up and running at ${url}"

                for ((i = 1; i <= max_attempts; i++)); do
                  local http_status
                  http_status=$(curl --insecure -I -s "${url}" | grep HTTP | awk '{print $2}')

                  if [ "${http_status}" -eq 200 ]; then
                    echo "Backstage is up and running!"
                    export BASE_URL="${url}"
                    echo "######## BASE URL ########"
                    echo "${BASE_URL}"
                    return 0
                  else
                    echo "Attempt ${i} of ${max_attempts}: Backstage not yet available (HTTP Status: ${http_status})"
                    sleep "${wait_seconds}"
                  fi
                done

                echo "Failed to reach Backstage at ${BASE_URL} after ${max_attempts} attempts." | tee -a "/tmp/${LOGFILE}"
                return 1
              }

              PASSWORD=$(cat ${PASSWORD_PATH})
              oc login ${API_SERVER_URL} --username=${USERNAME} --password=${PASSWORD} --insecure-skip-tls-verify

              oc create ns showcase
              export BASE_URL="redhat-developer-hub-showcase.$(oc get ingresses.config/cluster -o jsonpath='{.spec.domain}')"
              
              curl -sSLO https://raw.githubusercontent.com/rhdh-bot/openshift-helm-charts/redhat-developer-hub-1.3-124-CI/installation/install.sh && chmod +x install.sh
              ./install.sh 1.3-124-CI --namespace showcase --chartrepo

              check_backstage_running redhat-developer-hub showcase ${BASE_URL}
              git clone https://github.com/Omar-AlJaljuli/janus-idp-backstage-showcase-.git
              cd janus-idp-backstage-showcase- || exit
              git checkout "Konflux-CI" || exit
              cd e2e-tests/
              yarn install
              yarn playwright install

              cd playwright/e2e/
              yarn playwright test ./instance-health-check.spec.ts